apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:RAHUL-AMBARAGONDA/devops-team.git
    targetRevision: HEAD
    path: environments/dev
  destination:
    server: https://kubernetes.default.svc  # or your dev cluster API server URL
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
