apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculator-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RAHUL-AMBARAGONDA/new-gitops-repo
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: calculator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
