apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculator-app-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: calculator=docker.io/rahulambaragonda/calculator
    argocd-image-updater.argoproj.io/calculator.update-strategy: helm
    argocd-image-updater.argoproj.io/calculator.helm-values: image.tag
spec:
  project: default
  source:
    repoURL: https://github.com/RAHUL-AMBARAGONDA/devops-team.git
    targetRevision: main
    path: charts/calculator
    helm:
      valueFiles:
        - values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: calculator-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
