apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculator-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RAHUL-AMBARAGONDA/calculator-app
    targetRevision: main
    path: charts/calculator
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://<DEV-CLUSTER-API>
    namespace: calculator-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
