apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculator-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RAHUL-AMBARAGONDA/calculator-app.git
    targetRevision: main
    path: charts/calculator
    helm:
      valueFiles:
        - values.yaml          # or values-dev.yaml if you create env-specific overrides
  destination:
    server: https://kubernetes.default.svc  # dev cluster API
    namespace: calculator-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
